# Generated by Django 4.2.1 on 2023-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShop1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='toys/')),
            ],
        ),
    ]
